services:
  - type: web
    name: labcycle-api
    env: java      # Re-adicionado, pois é o valor oficial da documentação.
    plan: free     # Adicionado para ser explícito sobre o plano gratuito.
    
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"

    healthCheckPath: /actuator/health

    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false