services:
  - type: web
    name: labcycle-api
    # A linha 'env: java' foi removida para permitir a autodetecção.
    
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"

    healthCheckPath: /actuator/health

    envVars:
      # Adicionado "sync: false" para indicar que os valores são gerenciados no painel.
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false